// Command extract_cover_paths parses an HTML snapshot (e.g. a saved
// landing page of the decoy origin) and emits a Go source file containing
// a `dynamicCoverPaths` slice for package browser. The generated slice is
// merged with defaultCoverPaths via browser.CoverPathsPool() and consumed
// by client.WebSocketTransport.WarmupRequests to mimic NaiveProxy-style
// pre-upgrade asset fetches.
//
// Only same-origin paths (those starting with "/") are emitted. External
// URLs (https://..., //cdn.example.com/...) are skipped — emitting them
// from a same-origin warmup burst would itself be a fingerprintable
// anomaly.
//
// Usage:
//
//	go run ./tools/extract_cover_paths/ \
//	    -in skins/browser/testdata/<snapshot>.html \
//	    -out skins/browser/cover_paths_gen.go
package main

import (
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"strings"

	"golang.org/x/net/html"
)

// extractCoverPaths walks the HTML tree and returns same-origin paths
// referenced by <link href>, <script src>, and <img src> in document
// order. External URLs are skipped (same-origin filter is "path starts
// with /").
func extractCoverPaths(r io.Reader) ([]string, error) {
	doc, err := html.Parse(r)
	if err != nil {
		return nil, fmt.Errorf("parse html: %w", err)
	}
	var paths []string
	var walk func(*html.Node)
	walk = func(n *html.Node) {
		if n.Type == html.ElementNode {
			var attrName string
			switch n.Data {
			case "link":
				attrName = "href"
			case "script", "img":
				attrName = "src"
			}
			if attrName != "" {
				for _, a := range n.Attr {
					if a.Key == attrName && strings.HasPrefix(a.Val, "/") && !strings.HasPrefix(a.Val, "//") {
						paths = append(paths, a.Val)
					}
				}
			}
		}
		for c := n.FirstChild; c != nil; c = c.NextSibling {
			walk(c)
		}
	}
	walk(doc)
	return paths, nil
}

func writeGoFile(out string, paths []string) error {
	var b strings.Builder
	b.WriteString("// Code generated by extract_cover_paths. DO NOT EDIT.\n")
	b.WriteString("package browser\n\n")
	b.WriteString("// dynamicCoverPaths is the same-origin path list extracted from a\n")
	b.WriteString("// representative HTML snapshot of the decoy origin (datacanvases.com).\n")
	b.WriteString("// Combined with defaultCoverPaths by CoverPathsPool() and consumed by\n")
	b.WriteString("// WarmupRequests for NaiveProxy-style preamble traffic shape.\n")
	b.WriteString("var dynamicCoverPaths = []string{\n")
	for _, p := range paths {
		fmt.Fprintf(&b, "\t%q,\n", p)
	}
	b.WriteString("}\n")
	return os.WriteFile(out, []byte(b.String()), 0o644)
}

func main() {
	in := flag.String("in", "", "input HTML snapshot path")
	out := flag.String("out", "", "output .go file path")
	flag.Parse()
	if *in == "" || *out == "" {
		log.Fatal("both -in and -out are required")
	}
	f, err := os.Open(*in)
	if err != nil {
		log.Fatalf("open input: %v", err)
	}
	defer f.Close()
	paths, err := extractCoverPaths(f)
	if err != nil {
		log.Fatalf("extract: %v", err)
	}
	if len(paths) == 0 {
		log.Fatalf("no same-origin paths found in %s", *in)
	}
	if err := writeGoFile(*out, paths); err != nil {
		log.Fatalf("write output: %v", err)
	}
	fmt.Fprintf(os.Stderr, "extract_cover_paths: wrote %d paths to %s\n", len(paths), *out)
}
