package main

import (
	"flag"
	"fmt"
	"io"
	"net/http"
	"net/netip"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/nixavpn/shadowlink/client/bypassroute/cidrblob"
)

func main() {
	src := flag.String("source", "https://ftp.ripe.net/pub/stats/ripencc/delegated-ripencc-extended-latest", "URL or '-' for stdin")
	country := flag.String("country", "RU", "ISO country code")
	outBlob := flag.String("out-blob", "shadowlink/client/bypassroute/embedded_ru.bin", "output binary blob path")
	outGo := flag.String("out-go", "shadowlink/client/bypassroute/embedded.go", "output Go file path")
	dedupe := flag.Bool("dedupe", true, "dedupe and merge adjacent CIDRs")
	flag.Parse()

	var rdr io.Reader
	if *src == "-" {
		rdr = os.Stdin
	} else {
		resp, err := http.Get(*src)
		if err != nil {
			fmt.Fprintf(os.Stderr, "fetch %s: %v\n", *src, err)
			os.Exit(1)
		}
		defer resp.Body.Close()
		rdr = resp.Body
	}
	prefixes, err := ParseRIPELines(rdr, *country)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse: %v\n", err)
		os.Exit(1)
	}
	if *dedupe {
		prefixes = deduplicate(prefixes)
	}
	sort.Slice(prefixes, func(i, j int) bool {
		return prefixes[i].Addr().Less(prefixes[j].Addr())
	})

	blob, err := cidrblob.Encode(prefixes)
	if err != nil {
		fmt.Fprintf(os.Stderr, "encode: %v\n", err)
		os.Exit(1)
	}
	if err := os.MkdirAll(filepath.Dir(*outBlob), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*outBlob, blob, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write blob: %v\n", err)
		os.Exit(1)
	}

	gen := fmt.Sprintf(`// Code generated by tools/cidr-snapshot. DO NOT EDIT.
// Source: %s
// Country: %s
// Generated: %s
// Entries: %d

package bypassroute

import (
	_ "embed"
	"net/netip"

	"github.com/nixavpn/shadowlink/client/bypassroute/cidrblob"
)

//go:embed embedded_ru.bin
var embeddedRU []byte

// EmbeddedSize returns the number of CIDR prefixes in the embedded snapshot.
func EmbeddedSize() int { return len(embeddedRU) / 5 }

// loadEmbedded returns the parsed list of embedded RIPE RU CIDRs.
func loadEmbedded() ([]netip.Prefix, error) {
	return cidrblob.Decode(embeddedRU)
}
`, *src, *country, time.Now().UTC().Format(time.RFC3339), len(prefixes))
	if err := os.WriteFile(*outGo, []byte(strings.ReplaceAll(gen, "\r\n", "\n")), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write go: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %d prefixes (%d bytes blob) to %s\n", len(prefixes), len(blob), *outBlob)
}

// deduplicate removes prefixes covered by larger prefixes.
func deduplicate(in []netip.Prefix) []netip.Prefix {
	sort.Slice(in, func(i, j int) bool {
		if in[i].Bits() != in[j].Bits() {
			return in[i].Bits() < in[j].Bits()
		}
		return in[i].Addr().Less(in[j].Addr())
	})
	out := in[:0]
	for _, p := range in {
		covered := false
		for _, kept := range out {
			if kept.Bits() <= p.Bits() && kept.Contains(p.Addr()) {
				covered = true
				break
			}
		}
		if !covered {
			out = append(out, p)
		}
	}
	return out
}
