// Code generated by extract_cover_paths. DO NOT EDIT.
package browser

// dynamicCoverPaths is the same-origin path list extracted from a
// representative HTML snapshot of the decoy origin (datacanvases.com).
// Combined with defaultCoverPaths by CoverPathsPool() and consumed by
// WarmupRequests for NaiveProxy-style preamble traffic shape.
var dynamicCoverPaths = []string{
	"/css/app.css",
	"/css/theme.css",
	"/js/runtime.js",
	"/js/vendor.js",
	"/img/hero.webp",
	"/img/logo.svg",
	"/js/app.js",
}
