// Code generated by tools/cidr-snapshot. DO NOT EDIT.
// Source: https://ftp.ripe.net/pub/stats/ripencc/delegated-ripencc-extended-latest
// Country: RU
// Generated: 2026-05-02T13:19:02Z
// Entries: 11312

package bypassroute

import (
	_ "embed"
	"net/netip"

	"github.com/nixavpn/shadowlink/client/bypassroute/cidrblob"
)

//go:embed embedded_ru.bin
var embeddedRU []byte

// EmbeddedSize returns the number of CIDR prefixes in the embedded snapshot.
func EmbeddedSize() int { return len(embeddedRU) / 5 }

// loadEmbedded returns the parsed list of embedded RIPE RU CIDRs.
func loadEmbedded() ([]netip.Prefix, error) {
	return cidrblob.Decode(embeddedRU)
}
